### Register user
POST http://localhost:5003/auth/register
Content-Type: application/json

{
  "name": "tester",
  "email": "tester1@email.com",
  "password": "123321"
}

### Login user
POST http://localhost:5003/auth/login
Content-Type: application/json

{
  "email": "tester1@email.com",
  "password": "123321"
}